import Head from 'next/head'
import Image from 'next/image'
import FAQ from '../blog/FAQ'
import Privacy from '../blog/Privacy'
import Terms from '../blog/Terms'
import styles from '../styles/Home.module.css'
import How from '../blog/How'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>FifoLifo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
    <div className={styles.title}>
        <h1>FifoLifo</h1>  
    </div>
    <div className={styles.main}>
      <h2>How to Play?, FAQ, Terms of service AND Privacy policy </h2>
      <h3>FifoLifo is a free game where player will enter maximum words possible within 5 minutes. First alphabet of the word will be selected randomly from the previous word. Player can play this game again, only after 8 hours. Stars will be awarded on the basis of number of words entered, one spelling mistake and the game is over.</h3>
      </div>  
      {/* How to play */}
      <How />
      
      {/* FAQ */}
      <FAQ />

      {/* PRIVACY */}
      <Privacy />

      {/* Terms */}
      <Terms />
      
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
